sudo: required

language: generic

services:
  - docker

before_install:
  - |
    sudo docker run --rm -i \
    -e ARM_CLIENT_ID \
    -e ARM_CLIENT_SECRET \
    -e ARM_SUBSCRIPTION_ID \
    -e ARM_TENANT_ID \
    -v $(pwd):/app/ \
    -w /app/ \
    -t hashicorp/terraform:light apply -auto-approve
