sudo: required

language: generic

services:
  - docker

before_install:
  - |
    sudo docker run -i \
    -v $(pwd):/app/ \
    -w /app/ \
    -t hashicorp/terraform:light init

  - |
    sudo docker run -i \
    -e TF_VAR_ARM_CLIENT_ID \
    -e TF_VAR_ARM_CLIENT_SECRET \
    -e TF_VAR_ARM_SUBSCRIPTION_ID \
    -e TF_VAR_ARM_TENANT_ID \
    -v $(pwd):/app/ \
    -w /app/ \
    -t hashicorp/terraform:light apply -auto-approve
