sudo: required

language: ruby

services:
  - docker

before_install:
  - docker run --rm -i \
        -e ARM_CLIENT_ID \
        -e ARM_CLIENT_SECRET \
        -e ARM_SUBSCRIPTION_ID \
        -e ARM_TENANT_ID \
        -t hashicorp/terraform:light \
        -c "/bin/terraform version"
